language: ruby
rvm:
  - ruby-2.3.1
  - ruby-2.2.5
  - ruby-head
  - rubinius-3.62
  - rubinius
  - jruby-9.1.5.0
  - jruby-head
branches:
  only:
    - master
before_install:
  - git submodule update --init --recursive
  - gem install ffi
  - sudo wget http://packages.couchbase.com/releases/4.5.1/couchbase-server-enterprise_4.5.1-ubuntu14.04_amd64.deb
  - sudo dpkg -i couchbase-server-enterprise_4.5.1-ubuntu14.04_amd64.deb
  - sleep 4
  - sudo service couchbase-server status
  - /opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1:8091 --cluster-username=admin --cluster-password=password --cluster-ramsize=300 --cluster-index-ramsize=200 --cluster-fts-ramsize=200 --services=data,index,query,fts
before_script:
  - rake compile
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rubinius
sudo: required
dist: trusty
